/**
 * File: lib/demo/profile.ts
 * GENERATED by scripts/demo-profile-extract.mjs — do not hand-edit; edit the script and re-run.
 *
 * The demo generator reads THIS FILE and never the live tenant. That is the whole privacy design:
 * the promise that nothing identifying can survive rests on one artefact a human can read in a
 * sitting, not on runtime discipline in a query that anyone might later widen.
 *
 * ── WHAT IS DERIVED, AND FROM WHAT ──────────────────────────────────────────────────────────────
 * The NUMERIC SHAPE of one real GB independent's four months: hours, money, durations, mileage,
 * vehicle age, counts per job, weekday and start-hour spread, return interval, comeback rate.
 * Aggregates only — no row is copied, and every quantile is rounded (money to £5, hours to a
 * quarter, mileage to 1,000, durations to 5 minutes) so that no figure here is one job's number.
 *
 * ── WHAT IS AUTHORED, AND WHY ───────────────────────────────────────────────────────────────────
 * Every NAME. Vehicle makes and models, catalogue titles, the customer and street pools, and the
 * seasonal index. Two reasons, and the second matters more than the first:
 *   • the source garage is a MINI specialist (61% MINI, 24% BMW) with its own service tiering, and
 *     reproducing either would make the demo recognisably theirs;
 *   • it would also be WRONG. A general independent shown a MINI-heavy demo sees somebody else's
 *     business, and stops believing the rest of it.
 */

/**
 * ── EVERY MODEL CARRIES ITS OWN DATES ───────────────────────────────────────────────────────────
 * A flat list of model names plus a global year floor was not enough, and the failures were visible
 * in the data: 59 of 612 vehicles predated their own nameplate — a 2002 Vauxhall Insignia (launched
 * 2008), a 2002 SEAT Arona (2017), eleven Ford Pumas before the name came back in 2019. Age was
 * drawn from one distribution and the model from another, and nothing connected them.
 *
 *   from    the year the NAMEPLATE went on sale in the UK. A generated year is clamped up to it, so
 *           a Karoq is simply never old — which is true, and is why the clamp is not a distortion.
 *   ev      first year a battery-electric version existed, or null for never.
 *   hyb     first year a hybrid or mild-hybrid version existed, or null for never.
 *   diesel  whether it was ever sold here as a diesel.
 *
 * Approximate, authored, and occasionally arguable at the margins (mild hybrids especially). Being
 * a year out on the Corolla is invisible; being twenty years out on an Arona is not.
 */
export const VEHICLE_MIX = [
  { make: 'Ford', share: 14, models: [
    { name: 'Fiesta',          from: 1976, ev: null, hyb: 2020, diesel: true },
    { name: 'Focus',           from: 1998, ev: null, hyb: 2020, diesel: true },
    { name: 'Kuga',            from: 2008, ev: null, hyb: 2020, diesel: true },
    { name: 'Puma',            from: 2019, ev: 2024, hyb: 2019, diesel: true },
    { name: 'Transit Custom',  from: 2012, ev: 2023, hyb: 2019, diesel: true },
  ] },
  { make: 'Vauxhall', share: 11, models: [
    { name: 'Corsa',           from: 1993, ev: 2020, hyb: null, diesel: true },
    { name: 'Astra',           from: 1980, ev: 2023, hyb: 2022, diesel: true },
    { name: 'Mokka',           from: 2012, ev: 2021, hyb: null, diesel: true },
    { name: 'Insignia',        from: 2008, ev: null, hyb: null, diesel: true },
  ] },
  { make: 'Volkswagen', share: 11, models: [
    { name: 'Golf',            from: 1974, ev: 2014, hyb: 2015, diesel: true },
    { name: 'Polo',            from: 1975, ev: null, hyb: null, diesel: true },
    { name: 'Tiguan',          from: 2007, ev: null, hyb: 2021, diesel: true },
    { name: 'Passat',          from: 1973, ev: null, hyb: 2015, diesel: true },
    { name: 'Up',              from: 2011, ev: 2013, hyb: null, diesel: false },
  ] },
  { make: 'BMW', share: 8, models: [
    { name: '1 Series',        from: 2004, ev: null, hyb: null, diesel: true },
    { name: '3 Series',        from: 1975, ev: null, hyb: 2016, diesel: true },
    { name: '5 Series',        from: 1972, ev: null, hyb: 2017, diesel: true },
    { name: 'X1',              from: 2009, ev: 2023, hyb: 2020, diesel: true },
    { name: 'X3',              from: 2003, ev: null, hyb: 2020, diesel: true },
  ] },
  { make: 'Audi', share: 8, models: [
    { name: 'A1',              from: 2010, ev: null, hyb: null, diesel: true },
    { name: 'A3',              from: 1996, ev: null, hyb: 2014, diesel: true },
    { name: 'A4',              from: 1994, ev: null, hyb: 2019, diesel: true },
    { name: 'Q2',              from: 2016, ev: null, hyb: null, diesel: true },
    { name: 'Q3',              from: 2011, ev: null, hyb: 2020, diesel: true },
  ] },
  { make: 'Mercedes-Benz', share: 6, models: [
    { name: 'A-Class',         from: 1997, ev: null, hyb: 2019, diesel: true },
    { name: 'C-Class',         from: 1993, ev: null, hyb: 2015, diesel: true },
    { name: 'E-Class',         from: 1993, ev: null, hyb: 2016, diesel: true },
    { name: 'GLA',             from: 2013, ev: null, hyb: 2020, diesel: true },
  ] },
  { make: 'Toyota', share: 6, models: [
    { name: 'Yaris',           from: 1999, ev: null, hyb: 2012, diesel: false },
    { name: 'Corolla',         from: 1966, ev: null, hyb: 2019, diesel: true },
    { name: 'Aygo',            from: 2005, ev: null, hyb: null, diesel: false },
    { name: 'RAV4',            from: 1994, ev: null, hyb: 2016, diesel: true },
  ] },
  { make: 'Nissan', share: 6, models: [
    { name: 'Qashqai',         from: 2006, ev: null, hyb: 2022, diesel: true },
    { name: 'Juke',            from: 2010, ev: null, hyb: 2022, diesel: true },
    { name: 'Micra',           from: 1982, ev: null, hyb: null, diesel: false },
    { name: 'X-Trail',         from: 2001, ev: null, hyb: 2022, diesel: true },
  ] },
  { make: 'Peugeot', share: 5, models: [
    { name: '208',             from: 2012, ev: 2020, hyb: null, diesel: true },
    { name: '308',             from: 2007, ev: null, hyb: 2021, diesel: true },
    { name: '2008',            from: 2013, ev: 2020, hyb: null, diesel: true },
    { name: '3008',            from: 2009, ev: null, hyb: 2019, diesel: true },
  ] },
  { make: 'Kia', share: 5, models: [
    { name: 'Picanto',         from: 2004, ev: null, hyb: null, diesel: false },
    { name: 'Ceed',            from: 2006, ev: null, hyb: 2019, diesel: true },
    { name: 'Sportage',        from: 1993, ev: null, hyb: 2021, diesel: true },
    { name: 'Niro',            from: 2016, ev: 2018, hyb: 2016, diesel: false },
  ] },
  { make: 'Hyundai', share: 5, models: [
    { name: 'i10',             from: 2007, ev: null, hyb: null, diesel: false },
    { name: 'i20',             from: 2008, ev: null, hyb: 2020, diesel: true },
    { name: 'i30',             from: 2007, ev: null, hyb: 2019, diesel: true },
    { name: 'Tucson',          from: 2004, ev: null, hyb: 2021, diesel: true },
  ] },
  { make: 'Renault', share: 4, models: [
    { name: 'Clio',            from: 1990, ev: null, hyb: 2020, diesel: true },
    { name: 'Captur',          from: 2013, ev: null, hyb: 2020, diesel: true },
    { name: 'Megane',          from: 1995, ev: null, hyb: 2020, diesel: true },
  ] },
  { make: 'Honda', share: 3, models: [
    { name: 'Jazz',            from: 2001, ev: null, hyb: 2020, diesel: false },
    { name: 'Civic',           from: 1972, ev: null, hyb: 2022, diesel: true },
    { name: 'CR-V',            from: 1995, ev: null, hyb: 2019, diesel: true },
  ] },
  { make: 'Skoda', share: 3, models: [
    { name: 'Fabia',           from: 1999, ev: null, hyb: null, diesel: true },
    { name: 'Octavia',         from: 1996, ev: null, hyb: 2020, diesel: true },
    { name: 'Karoq',           from: 2017, ev: null, hyb: null, diesel: true },
  ] },
  { make: 'SEAT', share: 3, models: [
    { name: 'Ibiza',           from: 1984, ev: null, hyb: null, diesel: true },
    { name: 'Leon',            from: 1999, ev: null, hyb: 2020, diesel: true },
    { name: 'Arona',           from: 2017, ev: null, hyb: null, diesel: true },
  ] },
  { make: 'MINI', share: 2, models: [
    { name: 'Cooper',          from: 2001, ev: 2020, hyb: null, diesel: true },
    { name: 'Countryman',      from: 2010, ev: null, hyb: 2017, diesel: true },
  ] },
] as const;

/**
 * The fuel split a general independent's book SHOULD look like. It is a target for the whole fleet,
 * not a per-car probability: a model that was never sold as an EV redraws among the fuels it could
 * have had, with the weights renormalised. Falling back to petrol instead — the first attempt —
 * reshaped the book to 73/24/2/0.5 and left three electric cars in six hundred.
 *
 * The realised mix still cannot equal this exactly, and the reason is worth stating: a fleet whose
 * median car is eleven years old cannot be 4% electric, because those cars did not exist when most
 * of it was built. The gate asserts the realised mix against what the constraints ALLOW, and prints
 * both, rather than pretending the target is reachable.
 */
export const FUEL_MIX = [
  { fuel: 'Petrol', share: 58 },
  { fuel: 'Diesel', share: 30 },
  { fuel: 'Hybrid', share:  8 },
  { fuel: 'Electric', share: 4 },
] as const;


export const FIRST_NAMES = [
  'Alan', 'Amara', 'Andrew', 'Aisha', 'Barry', 'Beth', 'Callum', 'Carol', 'Chinelo', 'Craig',
  'Dawn', 'Dev', 'Eileen', 'Elliot', 'Fiona', 'Gary', 'Gemma', 'Hannah', 'Hassan', 'Ian',
  'Jasmine', 'Joan', 'Kayleigh', 'Keith', 'Lorraine', 'Marcus', 'Nadia', 'Neil', 'Olu', 'Paula',
  'Priya', 'Rachel', 'Ross', 'Sandra', 'Sean', 'Simone', 'Tariq', 'Tracey', 'Vikram', 'Wendy',
] as const;

export const LAST_NAMES = [
  'Ashton', 'Bailey', 'Bennett', 'Chowdhury', 'Clarke', 'Doyle', 'Ellis', 'Fletcher', 'Gill',
  'Hargreaves', 'Hunt', 'Iqbal', 'Jennings', 'Kaur', 'Lomax', 'Marsden', 'Nkemelu', 'Okafor',
  'Pearce', 'Quinn', 'Ramsay', 'Sutcliffe', 'Thorne', 'Underhill', 'Vance', 'Whitaker', 'Yates',
] as const;

/** An invented town. The postcode district is real-shaped but the streets are not. */
export const STREETS = [
  'Alder Row', 'Bramble Way', 'Carlyle Street', 'Dunmore Road', 'Elmfield Avenue',
  'Foundry Lane', 'Granby Terrace', 'Hillcrest Close', 'Ironside Way', 'Kestrel Drive',
  'Linden Grove', 'Marlow Street', 'Northgate', 'Orchard Rise', 'Pinfold Lane',
] as const;
export const TOWN = 'Marketbridge';
export const POSTCODE_AREA = 'MB';


/**
 * ── SEASONALITY IS AN ASSUMPTION, NOT A MEASUREMENT ─────────────────────────────────────────────
 * The source window is April to July. FOUR SUMMER MONTHS CANNOT PRODUCE AN ANNUAL CURVE, and
 * inventing one from them would be fabrication dressed as data. The source calibrates the LEVEL of
 * the demo's trade; this constant supplies its SHAPE, and it is stated rather than derived.
 *
 * The shape is the one structure that genuinely applies to any UK garage: MOT demand clusters on
 * the plate months. Cars first registered in March and September come back for their MOT in March
 * and September for the rest of their lives, so those are the peaks; August is the holiday dip and
 * late December is the trough because half the month is closed. Amplitude ±20%, which is visible on
 * a chart without being theatrical.
 *
 * Keyed on CALENDAR MONTH (index 0 = January), never on position in the rolling window — otherwise
 * the peak drifts as the demo ages.
 *
 * If this is ever replaced with something derived, DVSA publishes MOT volumes by month; that would
 * be a real source and this comment should then say so.
 */
export const SEASONAL_INDEX = [
  0.92, // Jan — quiet after Christmas, but the January MOT cohort is real
  0.98, // Feb
  1.20, // Mar — plate month: the biggest MOT cohort of the year
  1.05, // Apr
  1.02, // May
  1.00, // Jun
  1.00, // Jul
  0.85, // Aug — holidays, both sides of the ramp
  1.18, // Sep — the second plate month
  1.06, // Oct
  1.00, // Nov
  0.74, // Dec — 24 Dec to 2 Jan closed, and the weeks before it thin out
] as const;

/** ── DERIVED FROM THE SOURCE WINDOW ───────────────────────────────────────────────────────────
 *  Aggregates only. Money is rounded to £5, hours to a quarter, mileage to 1,000 and durations to
 *  5 minutes, so that no figure here is a transcription of one real job's number. */
export const SOURCE = {
  window: '2026-04-01 → 2026-08-01',
  invoices: 178,
  lines: 397,
} as const;

export const DISTRIBUTIONS = {
  "labourHoursPerJob": {
    "p10": 0.5,
    "p25": 0.5,
    "p50": 1.25,
    "p75": 3,
    "p90": 6.5,
    "max": 15
  },
  "partsCostPerJobGbp": {
    "p10": 0,
    "p25": 5,
    "p50": 35,
    "p75": 100,
    "p90": 255,
    "max": 980
  },
  "revenuePerJobGbp": {
    "p10": 65,
    "p25": 85,
    "p50": 190,
    "p75": 345,
    "p90": 825,
    "max": 2235
  },
  "linesPerJob": {
    "p10": 1,
    "p25": 1,
    "p50": 2,
    "p75": 3,
    "p90": 5,
    "max": 12
  },
  "bookingDurationMinutes": {
    "p10": 60,
    "p25": 60,
    "p50": 120,
    "p75": 180,
    "p90": 480,
    "max": 960
  },
  "vehicleMileage": {
    "p10": 30000,
    "p25": 47000,
    "p50": 70000,
    "p75": 99000,
    "p90": 131000,
    "max": 196000
  },
  "vehicleAgeYears": {
    "p10": 5,
    "p25": 8,
    "p50": 11,
    "p75": 14,
    "p90": 17,
    "max": 24
  }
} as const;

/** Booked diary time ÷ labour hours sold. The footprint is LONGER than the work: road test, parts
 *  wait, cleanup. Book only the charged hours and the diary looks half empty while the utilisation
 *  tile says 62% — the first contradiction anyone would notice. */
export const FOOTPRINT_RATIO = 1.32;

/** Line composition, as a share of all lines. */
export const LINE_TYPE_MIX = {
  "fixed": 50.1,
  "part": 31,
  "labour": 18.9
} as const;

/** Invoices by weekday, Sunday-first. Derived from the invoice's EFFECTIVE date — job-card
 *  created_at is when the owner typed it in (weekend catch-up sessions), not when work happened. */
export const WEEKDAY_SHARE = [1.1,17.4,18.5,14.6,18.5,28.1,1.7] as const;

/** Where bookings start. TMBS puts 55% at 09:00 on the dot and nothing at 13:00 — the lunch gap is
 *  real and kept; the on-the-hour habit is not reproduced (the generator uses a quarter-hour grid,
 *  which is what a diary actually looks like). */
export const START_HOUR_SHARE = {
  "8": 0.5,
  "9": 58.1,
  "10": 5.1,
  "11": 14.4,
  "12": 0.5,
  "14": 15.8,
  "15": 3.7,
  "16": 1.9
} as const;

/** How often a customer comes back. The 4-month window saw 17.1% return at least once;
 *  the generator needs the INTERVAL, not the rate, because the same interval produces a very
 *  different rate over 12 months than over 4. */
export const RETURN_INTERVAL_MONTHS = 11;

/** Rework. A comeback is £0 revenue with the parts cost still landing (lib/comeback). */
export const COMEBACK_RATE_PCT = 3.2;
export const WARRANTY_INVOICE_RATE_PCT = 2.2;
/** Negative lines — discount codes and goodwill. Worth reproducing: they exercise real features. */
export const NEGATIVE_LINE_RATE_PCT = 5.5;

/** ── JOB ARCHETYPES ──────────────────────────────────────────────────────────────────────────
 *  Titles are AUTHORED. Prices, parts costs and labour hours are DERIVED medians. TMBS's own
 *  Bronze/Silver/Gold/Platinum tiering is deliberately not reproduced — it is theirs, and it is
 *  recognisable. */
export const ARCHETYPES = [
  {
    "key": "mot",
    "title": "MOT test",
    "itemType": "fixed",
    "outsourcedLabour": true,
    "priceGbp": 50,
    "partsCostGbp": 35,
    "labourHours": 0,
    "shareOfLines": 5.5
  },
  {
    "key": "service_minor",
    "title": "Interval service — minor",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 125,
    "partsCostGbp": 30,
    "labourHours": 0.75,
    "shareOfLines": 7.1
  },
  {
    "key": "service_major",
    "title": "Interval service — major",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 290,
    "partsCostGbp": 65,
    "labourHours": 2,
    "shareOfLines": 5.5
  },
  {
    "key": "brake_fluid",
    "title": "Brake fluid change",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 85,
    "partsCostGbp": 5,
    "labourHours": 0.5,
    "shareOfLines": 5.5
  },
  {
    "key": "diagnostic",
    "title": "Diagnostic investigation",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 65,
    "partsCostGbp": 5,
    "labourHours": 0.5,
    "shareOfLines": 10.6
  },
  {
    "key": "aircon",
    "title": "Air-conditioning regas",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 65,
    "partsCostGbp": 10,
    "labourHours": 0.5,
    "shareOfLines": 3
  },
  {
    "key": "brakes_front",
    "title": "Front brake pads & discs",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 315,
    "partsCostGbp": 100,
    "labourHours": 1,
    "shareOfLines": 1.5
  },
  {
    "key": "brakes_rear",
    "title": "Rear brake pads & shoes",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 150,
    "partsCostGbp": 30,
    "labourHours": 1,
    "shareOfLines": 2.3
  },
  {
    "key": "battery",
    "title": "Battery supply & fit",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 150,
    "partsCostGbp": 95,
    "labourHours": 0.5,
    "shareOfLines": 0.8
  },
  {
    "key": "timing",
    "title": "Timing chain replacement",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 710,
    "partsCostGbp": 125,
    "labourHours": 5,
    "shareOfLines": 2.3
  },
  {
    "key": "headwork",
    "title": "Cylinder head overhaul",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 1000,
    "partsCostGbp": 145,
    "labourHours": 8,
    "shareOfLines": 1.3
  },
  {
    "key": "valet",
    "title": "Valet",
    "itemType": "fixed",
    "outsourcedLabour": true,
    "priceGbp": 20,
    "partsCostGbp": 5,
    "labourHours": 0.25,
    "shareOfLines": 1.3
  }
] as const;

export type Archetype = (typeof ARCHETYPES)[number];
