/**
 * File: lib/demo/profile.ts
 * GENERATED by scripts/demo-profile-extract.mjs — do not hand-edit; edit the script and re-run.
 *
 * The demo generator reads THIS FILE and never the live tenant. That is the whole privacy design:
 * the promise that nothing identifying can survive rests on one artefact a human can read in a
 * sitting, not on runtime discipline in a query that anyone might later widen.
 *
 * ── WHAT IS DERIVED, AND FROM WHAT ──────────────────────────────────────────────────────────────
 * The NUMERIC SHAPE of one real GB independent's four months: hours, money, durations, mileage,
 * vehicle age, counts per job, weekday and start-hour spread, return interval, comeback rate.
 * Aggregates only — no row is copied, and every quantile is rounded (money to £5, hours to a
 * quarter, mileage to 1,000, durations to 5 minutes) so that no figure here is one job's number.
 *
 * ── WHAT IS AUTHORED, AND WHY ───────────────────────────────────────────────────────────────────
 * Every NAME. Vehicle makes and models, catalogue titles, the customer and street pools, and the
 * seasonal index. Two reasons, and the second matters more than the first:
 *   • the source garage is a MINI specialist (61% MINI, 24% BMW) with its own service tiering, and
 *     reproducing either would make the demo recognisably theirs;
 *   • it would also be WRONG. A general independent shown a MINI-heavy demo sees somebody else's
 *     business, and stops believing the rest of it.
 */

export const VEHICLE_MIX = [
  { make: 'Ford',          share: 14, models: ['Fiesta', 'Focus', 'Kuga', 'Puma', 'Transit Custom'] },
  { make: 'Vauxhall',      share: 11, models: ['Corsa', 'Astra', 'Mokka', 'Insignia'] },
  { make: 'Volkswagen',    share: 11, models: ['Golf', 'Polo', 'Tiguan', 'Passat', 'Up'] },
  { make: 'BMW',           share:  8, models: ['1 Series', '3 Series', '5 Series', 'X1', 'X3'] },
  { make: 'Audi',          share:  8, models: ['A1', 'A3', 'A4', 'Q2', 'Q3'] },
  { make: 'Mercedes-Benz', share:  6, models: ['A-Class', 'C-Class', 'E-Class', 'GLA'] },
  { make: 'Toyota',        share:  6, models: ['Yaris', 'Corolla', 'Aygo', 'RAV4'] },
  { make: 'Nissan',        share:  6, models: ['Qashqai', 'Juke', 'Micra', 'X-Trail'] },
  { make: 'Peugeot',       share:  5, models: ['208', '308', '2008', '3008'] },
  { make: 'Kia',           share:  5, models: ['Picanto', 'Ceed', 'Sportage', 'Niro'] },
  { make: 'Hyundai',       share:  5, models: ['i10', 'i20', 'i30', 'Tucson'] },
  { make: 'Renault',       share:  4, models: ['Clio', 'Captur', 'Megane'] },
  { make: 'Honda',         share:  3, models: ['Jazz', 'Civic', 'CR-V'] },
  { make: 'Skoda',         share:  3, models: ['Fabia', 'Octavia', 'Karoq'] },
  { make: 'SEAT',          share:  3, models: ['Ibiza', 'Leon', 'Arona'] },
  { make: 'MINI',          share:  2, models: ['Cooper', 'Countryman'] },
] as const;

/** Fuel split, AUTHORED to a plausible GB independent's book — an older parc than the new-car
 *  market, so still petrol-heavy with a thin but present electrified tail. */
export const FUEL_MIX = [
  { fuel: 'Petrol', share: 58 },
  { fuel: 'Diesel', share: 30 },
  { fuel: 'Hybrid', share:  8 },
  { fuel: 'Electric', share: 4 },
] as const;

/**
 * ── FUEL HAS TO SUIT THE CAR, OR A MECHANIC SPOTS IT IN A SECOND ────────────────────────────────
 * Drawing fuel independently of the model produced a diesel Toyota Aygo and a 2015 electric
 * Peugeot 2008 in the first generated tenant. Neither has ever existed, and the audience for this
 * demo is people who would know that immediately — one implausible row costs more credibility than
 * the other nine hundred earn.
 *
 * PETROL_ONLY: city cars and small petrol models never sold as diesels in the UK.
 * EV_FROM / HYBRID_FROM: the earliest model year at which an electrified version is plausible at
 * all. A car older than that falls back to petrol or diesel.
 */
export const PETROL_ONLY = [
  'Aygo', 'Picanto', 'i10', 'Up', 'Micra', 'Jazz', 'Yaris', 'Ibiza', 'Fabia', 'Panda',
] as const;
export const EV_FROM = 2016;
export const HYBRID_FROM = 2012;
/** Models that are electric-capable at all — everything else stays combustion whatever the year. */
export const EV_CAPABLE = [
  'Corsa', 'Mokka', 'Astra', '208', '2008', 'Zoe', 'Niro', 'Kona', 'Leaf', 'Golf', 'Up',
  'i3', 'X1', 'A-Class', 'Puma', 'Fiesta', 'Captur', 'Clio', 'Yaris', 'Corolla',
] as const;


export const FIRST_NAMES = [
  'Alan', 'Amara', 'Andrew', 'Aisha', 'Barry', 'Beth', 'Callum', 'Carol', 'Chinelo', 'Craig',
  'Dawn', 'Dev', 'Eileen', 'Elliot', 'Fiona', 'Gary', 'Gemma', 'Hannah', 'Hassan', 'Ian',
  'Jasmine', 'Joan', 'Kayleigh', 'Keith', 'Lorraine', 'Marcus', 'Nadia', 'Neil', 'Olu', 'Paula',
  'Priya', 'Rachel', 'Ross', 'Sandra', 'Sean', 'Simone', 'Tariq', 'Tracey', 'Vikram', 'Wendy',
] as const;

export const LAST_NAMES = [
  'Ashton', 'Bailey', 'Bennett', 'Chowdhury', 'Clarke', 'Doyle', 'Ellis', 'Fletcher', 'Gill',
  'Hargreaves', 'Hunt', 'Iqbal', 'Jennings', 'Kaur', 'Lomax', 'Marsden', 'Nkemelu', 'Okafor',
  'Pearce', 'Quinn', 'Ramsay', 'Sutcliffe', 'Thorne', 'Underhill', 'Vance', 'Whitaker', 'Yates',
] as const;

/** An invented town. The postcode district is real-shaped but the streets are not. */
export const STREETS = [
  'Alder Row', 'Bramble Way', 'Carlyle Street', 'Dunmore Road', 'Elmfield Avenue',
  'Foundry Lane', 'Granby Terrace', 'Hillcrest Close', 'Ironside Way', 'Kestrel Drive',
  'Linden Grove', 'Marlow Street', 'Northgate', 'Orchard Rise', 'Pinfold Lane',
] as const;
export const TOWN = 'Marketbridge';
export const POSTCODE_AREA = 'MB';


/**
 * ── SEASONALITY IS AN ASSUMPTION, NOT A MEASUREMENT ─────────────────────────────────────────────
 * The source window is April to July. FOUR SUMMER MONTHS CANNOT PRODUCE AN ANNUAL CURVE, and
 * inventing one from them would be fabrication dressed as data. The source calibrates the LEVEL of
 * the demo's trade; this constant supplies its SHAPE, and it is stated rather than derived.
 *
 * The shape is the one structure that genuinely applies to any UK garage: MOT demand clusters on
 * the plate months. Cars first registered in March and September come back for their MOT in March
 * and September for the rest of their lives, so those are the peaks; August is the holiday dip and
 * late December is the trough because half the month is closed. Amplitude ±20%, which is visible on
 * a chart without being theatrical.
 *
 * Keyed on CALENDAR MONTH (index 0 = January), never on position in the rolling window — otherwise
 * the peak drifts as the demo ages.
 *
 * If this is ever replaced with something derived, DVSA publishes MOT volumes by month; that would
 * be a real source and this comment should then say so.
 */
export const SEASONAL_INDEX = [
  0.92, // Jan — quiet after Christmas, but the January MOT cohort is real
  0.98, // Feb
  1.20, // Mar — plate month: the biggest MOT cohort of the year
  1.05, // Apr
  1.02, // May
  1.00, // Jun
  1.00, // Jul
  0.85, // Aug — holidays, both sides of the ramp
  1.18, // Sep — the second plate month
  1.06, // Oct
  1.00, // Nov
  0.74, // Dec — 24 Dec to 2 Jan closed, and the weeks before it thin out
] as const;

/** ── DERIVED FROM THE SOURCE WINDOW ───────────────────────────────────────────────────────────
 *  Aggregates only. Money is rounded to £5, hours to a quarter, mileage to 1,000 and durations to
 *  5 minutes, so that no figure here is a transcription of one real job's number. */
export const SOURCE = {
  window: '2026-04-01 → 2026-08-01',
  invoices: 178,
  lines: 397,
} as const;

export const DISTRIBUTIONS = {
  "labourHoursPerJob": {
    "p10": 0.5,
    "p25": 0.5,
    "p50": 1.25,
    "p75": 3,
    "p90": 6.5,
    "max": 15
  },
  "partsCostPerJobGbp": {
    "p10": 0,
    "p25": 5,
    "p50": 35,
    "p75": 100,
    "p90": 255,
    "max": 980
  },
  "revenuePerJobGbp": {
    "p10": 65,
    "p25": 85,
    "p50": 190,
    "p75": 345,
    "p90": 825,
    "max": 2235
  },
  "linesPerJob": {
    "p10": 1,
    "p25": 1,
    "p50": 2,
    "p75": 3,
    "p90": 5,
    "max": 12
  },
  "bookingDurationMinutes": {
    "p10": 60,
    "p25": 60,
    "p50": 120,
    "p75": 180,
    "p90": 480,
    "max": 960
  },
  "vehicleMileage": {
    "p10": 30000,
    "p25": 47000,
    "p50": 70000,
    "p75": 99000,
    "p90": 131000,
    "max": 196000
  },
  "vehicleAgeYears": {
    "p10": 5,
    "p25": 8,
    "p50": 11,
    "p75": 14,
    "p90": 17,
    "max": 24
  }
} as const;

/** Booked diary time ÷ labour hours sold. The footprint is LONGER than the work: road test, parts
 *  wait, cleanup. Book only the charged hours and the diary looks half empty while the utilisation
 *  tile says 62% — the first contradiction anyone would notice. */
export const FOOTPRINT_RATIO = 1.34;

/** Line composition, as a share of all lines. */
export const LINE_TYPE_MIX = {
  "fixed": 50.1,
  "part": 31,
  "labour": 18.9
} as const;

/** Invoices by weekday, Sunday-first. Derived from the invoice's EFFECTIVE date — job-card
 *  created_at is when the owner typed it in (weekend catch-up sessions), not when work happened. */
export const WEEKDAY_SHARE = [1.1,17.4,18.5,14.6,18.5,28.1,1.7] as const;

/** Where bookings start. TMBS puts 55% at 09:00 on the dot and nothing at 13:00 — the lunch gap is
 *  real and kept; the on-the-hour habit is not reproduced (the generator uses a quarter-hour grid,
 *  which is what a diary actually looks like). */
export const START_HOUR_SHARE = {
  "8": 0.5,
  "9": 57.3,
  "10": 5.3,
  "11": 15,
  "12": 0.5,
  "14": 15.5,
  "15": 3.9,
  "16": 1.9
} as const;

/** How often a customer comes back. The 4-month window saw 17.1% return at least once;
 *  the generator needs the INTERVAL, not the rate, because the same interval produces a very
 *  different rate over 12 months than over 4. */
export const RETURN_INTERVAL_MONTHS = 11;

/** Rework. A comeback is £0 revenue with the parts cost still landing (lib/comeback). */
export const COMEBACK_RATE_PCT = 3.3;
export const WARRANTY_INVOICE_RATE_PCT = 2.2;
/** Negative lines — discount codes and goodwill. Worth reproducing: they exercise real features. */
export const NEGATIVE_LINE_RATE_PCT = 5.5;

/** ── JOB ARCHETYPES ──────────────────────────────────────────────────────────────────────────
 *  Titles are AUTHORED. Prices, parts costs and labour hours are DERIVED medians. TMBS's own
 *  Bronze/Silver/Gold/Platinum tiering is deliberately not reproduced — it is theirs, and it is
 *  recognisable. */
export const ARCHETYPES = [
  {
    "key": "mot",
    "title": "MOT test",
    "itemType": "fixed",
    "outsourcedLabour": true,
    "priceGbp": 50,
    "partsCostGbp": 35,
    "labourHours": 0,
    "shareOfLines": 5.5
  },
  {
    "key": "service_minor",
    "title": "Interval service — minor",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 125,
    "partsCostGbp": 30,
    "labourHours": 0.75,
    "shareOfLines": 7.1
  },
  {
    "key": "service_major",
    "title": "Interval service — major",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 290,
    "partsCostGbp": 65,
    "labourHours": 2,
    "shareOfLines": 5.5
  },
  {
    "key": "brake_fluid",
    "title": "Brake fluid change",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 85,
    "partsCostGbp": 5,
    "labourHours": 0.5,
    "shareOfLines": 5.5
  },
  {
    "key": "diagnostic",
    "title": "Diagnostic investigation",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 65,
    "partsCostGbp": 0,
    "labourHours": 0.5,
    "shareOfLines": 10.6
  },
  {
    "key": "aircon",
    "title": "Air-conditioning regas",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 65,
    "partsCostGbp": 10,
    "labourHours": 0.5,
    "shareOfLines": 3
  },
  {
    "key": "brakes_front",
    "title": "Front brake pads & discs",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 315,
    "partsCostGbp": 100,
    "labourHours": 1,
    "shareOfLines": 1.5
  },
  {
    "key": "brakes_rear",
    "title": "Rear brake pads & shoes",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 150,
    "partsCostGbp": 30,
    "labourHours": 1,
    "shareOfLines": 2.3
  },
  {
    "key": "battery",
    "title": "Battery supply & fit",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 150,
    "partsCostGbp": 95,
    "labourHours": 0.5,
    "shareOfLines": 0.8
  },
  {
    "key": "timing",
    "title": "Timing chain replacement",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 710,
    "partsCostGbp": 125,
    "labourHours": 5,
    "shareOfLines": 2.3
  },
  {
    "key": "headwork",
    "title": "Cylinder head overhaul",
    "itemType": "fixed",
    "outsourcedLabour": false,
    "priceGbp": 1000,
    "partsCostGbp": 145,
    "labourHours": 8,
    "shareOfLines": 1.3
  },
  {
    "key": "valet",
    "title": "Valet",
    "itemType": "fixed",
    "outsourcedLabour": true,
    "priceGbp": 20,
    "partsCostGbp": 0,
    "labourHours": 0.25,
    "shareOfLines": 1.3
  }
] as const;

export type Archetype = (typeof ARCHETYPES)[number];
