/**
 * File: lib/vat-summary-pdf.tsx
 * The A4 "VAT on sales" summary PDF for the accountant. OUTPUT VAT ONLY — the disclaimer is printed
 * prominently so it can never be mistaken for a complete VAT return. @react-pdf/renderer, server-only.
 */
import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import type { VatSummary } from '@/lib/vat-summary';
import { formatMoney } from '@/lib/format-money';

const S = StyleSheet.create({
  page: { padding: 48, fontSize: 10, fontFamily: 'Helvetica', color: '#111827' },
  h1: { fontSize: 18, fontFamily: 'Helvetica-Bold' },
  muted: { color: '#6b7280' },
  disclaimer: { marginTop: 10, marginBottom: 18, padding: 10, backgroundColor: '#fef3c7', borderWidth: 1, borderColor: '#f59e0b', fontSize: 9, color: '#92400e' },
  totalsBox: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 4, padding: 14, marginBottom: 18 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  grand: { borderTopWidth: 1, borderTopColor: '#e5e7eb', marginTop: 6, paddingTop: 6, fontFamily: 'Helvetica-Bold', fontSize: 13 },
  th: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingVertical: 6, marginTop: 8 },
  row: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#f3f4f6', paddingVertical: 6 },
  cRate: { flex: 2 }, cNet: { flex: 3, textAlign: 'right' }, cVat: { flex: 3, textAlign: 'right' }, cLines: { flex: 2, textAlign: 'right' },
  label: { fontSize: 7, textTransform: 'uppercase', color: '#6b7280', letterSpacing: 0.5 },
  footer: { position: 'absolute', bottom: 32, left: 48, right: 48, textAlign: 'center', fontSize: 8, color: '#9ca3af' },
});

export type VatPdfInput = VatSummary & { businessName: string; vatNumber: string | null; periodLabel: string; currency: string; locale: string };

function VatSummaryPdf({ d }: { d: VatPdfInput }) {
  const gbp = (p: number) => formatMoney(p, { currency: d.currency, locale: d.locale }); // tenant currency, not hardcoded £
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <Text style={S.h1}>VAT on sales</Text>
        <Text style={S.muted}>{d.businessName}{d.vatNumber ? ` · VAT ${d.vatNumber}` : ''}</Text>
        <Text style={{ marginTop: 4 }}>Period: {d.periodLabel}</Text>

        <Text style={S.disclaimer}>
          VAT on sales for the period — provide to your accountant for your VAT return. This is a
          reconciliation aid, NOT a complete VAT return: it shows OUTPUT VAT on your issued sales
          invoices only, and EXCLUDES purchase / input VAT (parts, overheads and other purchases).
        </Text>

        <View style={S.totalsBox}>
          <View style={S.totalRow}><Text style={S.muted}>Total sales (ex-VAT)</Text><Text>{gbp(d.netPennies)}</Text></View>
          <View style={S.totalRow}><Text style={S.muted}>Invoices</Text><Text>{d.invoiceCount}</Text></View>
          <View style={[S.totalRow, S.grand]}><Text>Total output VAT</Text><Text>{gbp(d.vatPennies)}</Text></View>
        </View>

        <Text style={S.label}>Breakdown by VAT rate</Text>
        <View style={S.th}>
          <Text style={[S.cRate, S.label]}>Rate</Text><Text style={[S.cNet, S.label]}>Net (ex-VAT)</Text>
          <Text style={[S.cVat, S.label]}>VAT</Text><Text style={[S.cLines, S.label]}>Lines</Text>
        </View>
        {d.byRate.length === 0 && <Text style={{ paddingVertical: 8, ...S.muted }}>No sales invoices in this period.</Text>}
        {d.byRate.map((r) => (
          <View style={S.row} key={r.ratePercent}>
            <Text style={S.cRate}>{r.ratePercent}%</Text><Text style={S.cNet}>{gbp(r.netPennies)}</Text>
            <Text style={S.cVat}>{gbp(r.vatPennies)}</Text><Text style={S.cLines}>{r.lineCount}</Text>
          </View>
        ))}

        <Text style={S.footer}>Generated by GreaseDesk · VAT on sales (output VAT) only · not a VAT return</Text>
      </Page>
    </Document>
  );
}

export function renderVatSummaryPdf(d: VatPdfInput): Promise<Buffer> {
  return renderToBuffer(<VatSummaryPdf d={d} />);
}
