-- COSTS: a definition, an append-only rate series, and generated occurrences.
--
-- Replaces the dateless Overhead register for the figures. Overhead itself is LEFT IN PLACE: three
-- other tenants still have rows on it (two demo tenants whose figures are calibrated inputs, one of
-- them under an active presentation freeze), and dropping the table as a side effect of this change
-- would take their data with it. Retiring it is its own decision, made deliberately.
--
-- Generated by `prisma migrate diff` and READ before keeping: only the intended objects, no stray
-- DROP or ALTER swept in from unrelated drift.
-- CreateEnum
CREATE TYPE "CostCadence" AS ENUM ('monthly', 'quarterly', 'annual');

-- CreateEnum
CREATE TYPE "CostCharge" AS ENUM ('spread', 'falls');

-- AlterTable
ALTER TABLE "CostAllocation" ADD COLUMN     "cost_id" TEXT;

-- CreateTable
CREATE TABLE "Cost" (
    "id" TEXT NOT NULL,
    "group_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cadence" "CostCadence" NOT NULL,
    "charge" "CostCharge" NOT NULL DEFAULT 'spread',
    "active_from" TIMESTAMP(3) NOT NULL,
    "active_to" TIMESTAMP(3),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Cost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CostRate" (
    "id" TEXT NOT NULL,
    "cost_id" TEXT NOT NULL,
    "effective_from" TIMESTAMP(3) NOT NULL,
    "amount_pennies" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CostRate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CostInstance" (
    "id" TEXT NOT NULL,
    "cost_id" TEXT NOT NULL,
    "period_start" TIMESTAMP(3) NOT NULL,
    "period_end" TIMESTAMP(3) NOT NULL,
    "due_on" TIMESTAMP(3) NOT NULL,
    "amount_pennies" INTEGER NOT NULL,
    "is_estimate" BOOLEAN NOT NULL DEFAULT true,
    "edited_at" TIMESTAMP(3),
    "edited_by" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CostInstance_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Cost_group_id_is_active_idx" ON "Cost"("group_id", "is_active");

-- CreateIndex
CREATE INDEX "CostRate_cost_id_effective_from_idx" ON "CostRate"("cost_id", "effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "CostRate_cost_id_effective_from_key" ON "CostRate"("cost_id", "effective_from");

-- CreateIndex
CREATE INDEX "CostInstance_cost_id_period_start_idx" ON "CostInstance"("cost_id", "period_start");

-- CreateIndex
CREATE INDEX "CostInstance_period_start_idx" ON "CostInstance"("period_start");

-- CreateIndex
CREATE UNIQUE INDEX "CostInstance_cost_id_period_start_key" ON "CostInstance"("cost_id", "period_start");

-- CreateIndex
CREATE UNIQUE INDEX "CostAllocation_cost_id_site_id_key" ON "CostAllocation"("cost_id", "site_id");

-- AddForeignKey
ALTER TABLE "Cost" ADD CONSTRAINT "Cost_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CostRate" ADD CONSTRAINT "CostRate_cost_id_fkey" FOREIGN KEY ("cost_id") REFERENCES "Cost"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CostInstance" ADD CONSTRAINT "CostInstance_cost_id_fkey" FOREIGN KEY ("cost_id") REFERENCES "Cost"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CostAllocation" ADD CONSTRAINT "CostAllocation_cost_id_fkey" FOREIGN KEY ("cost_id") REFERENCES "Cost"("id") ON DELETE CASCADE ON UPDATE CASCADE;

